myapp/urls.py
from django.urls import path

from myapp.views import *

app_name = 'myapp'

urlpatterns = [

    path('logout/', logout, name='logout'),


    path('',postListView, name = 'home_view'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),

    path('add/', PostCreateView.as_view(), name = 'add'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name = 'update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name = 'delete'),

    path('<int:postId>/UComment_<int:pk>',CommentUpdateView.as_view(), name = 'comment_update'),
    path('<int:postId>/DComment_<int:pk>',CommentDeleteView.as_view(), name = 'comment_delete'),

    path('<int:postId>/CRepost/',RePostCreate.as_view(), name = 'add_repost'),
    path('<int:PcommentId>/addRecomment/',ReCommentCreateView.as_view(), name = 'add_recomment'),
]

newSite/urls.py
from django.contrib import admin
from django.urls import path, include
from newSite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('home/', include('myapp.urls')),

    path('accounts/', include('django.contrib.auth.urls'), name = 'login'),
    path('accounts/register/', UserCreateView.as_view(), name = 'register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),

]

polls/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # ex) /polls/
    path('', views.IndexView.as_view(), name = 'index'),

    path('logout/', views.logout, name = 'logout'),

    # ex) /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),

    #ex) /polls/5/results/
    path('<int:question_id>/results/', views.results, name = 'results'),

    #ex) /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name = 'vote'),

]

polls/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return  timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'published recently?'


    def __str__(self):
        return self.question_text


class Choice(models.Model):
    #question 속성은 Question 객체를 포린키로 가져온다. -> question.choice_set 가능
    question = models.ForeignKey(Question ,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return  self.choice_text

polls/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.utils import timezone

from .models import Question, Choice
from django.urls import reverse

from django.views import generic
from django.contrib.auth import logout as django_logout
from django.shortcuts import redirect
# Create your views here.
'''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list' : latest_question_list,
    }

    return HttpResponse(template.render(context, request))
'''

'''
#render version
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    context = {
        'latest_question_list' : latest_question_list
    }

    return render(request, 'polls/index.html', context)

#
'''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return  Question.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5]


'''
def detail(request, question_id):
    try:
        question = Question.objects.get(pk = question_id)
        context = {
            'question' : question
        }
    except:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.hml', context)
'''
'''
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question
    }
    return render(request, 'polls/detail.html', context)
'''
def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html',{'question' : question})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'





def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        #get data from                                            input name
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question' : question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))


def logout(request):
    django_logout(request)
    return redirect('polls:index')

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type = "radio"
               name = "choice"
               id = "choice{{ forloop.counter }}"
               value = "{{ choice.id }}">
        <label for = "choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if user.is_active %}
<h4 class = "welcome">
    Welcome,
    <strong>{{ user.get_username }}</strong>
    /
    <a href={%  url 'polls:logout' %}>logout</a>
</h4>
{% else %}
<a href={%  url 'login' %}>login</a>
{% endif %}



{%  load static %}
<link rel= "stylesheet" type = "text/css" href = "{% static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{%  url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }}
            {% if choice.votes == 0 %}
            vote
            {% else %}
            vote{{ choice.votes|pluralize }}</li>
            {% endif %}
    {% endfor %}

</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>