myapp/urls.py
from django.urls import path

from myapp.views import *

app_name = 'myapp'

urlpatterns = [

    path('logout/', logout, name='logout'),


    path('',postListView, name = 'home_view'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),

    path('add/', PostCreateView.as_view(), name = 'add'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name = 'update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name = 'delete'),

    path('<int:postId>/UComment_<int:pk>',CommentUpdateView.as_view(), name = 'comment_update'),
    path('<int:postId>/DComment_<int:pk>',CommentDeleteView.as_view(), name = 'comment_delete'),

    path('<int:postId>/CRepost/',RePostCreate.as_view(), name = 'add_repost'),
    path('<int:PcommentId>/addRecomment/',ReCommentCreateView.as_view(), name = 'add_recomment'),
]

newSite/urls.py
from django.contrib import admin
from django.urls import path, include
from newSite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('home/', include('myapp.urls')),

    path('accounts/', include('django.contrib.auth.urls'), name = 'login'),
    path('accounts/register/', UserCreateView.as_view(), name = 'register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),

]

myapp/models.py
import null as null
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
import datetime

# Create your models here.
class Post(models.Model):
    title_text = models.CharField(max_length=50)
    writer = models.ForeignKey(User, null= True, on_delete=models.CASCADE)

    create_date = models.DateTimeField('Created date', auto_now_add= True)
    modify_date = models.DateTimeField('Modified date')
    content = models.TextField("CONTENT")

    parent_post = models.ForeignKey('self', null= True, blank= True, on_delete=models.CASCADE)
    g_order = models.IntegerField(default=0, blank= True)
    depth = models.IntegerField(default=0, blank= True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title_text

    def get_absolute_url(self):
        return reverse("myapp:post_detail",args=(self.id,))

    def get_comment_count(self):
        comments = Comment.objects.filter(linkedPost_id=self.id)
        return len(comments)

    def initRePost(self, parentPost):
        self.parent_post = parentPost
        self.g_order = parentPost.g_order
        self.depth = 1
        return


class Comment(models.Model):
    linkedPost = models.ForeignKey(Post, on_delete=models.CASCADE)

    create_date = models.DateTimeField('Created date', auto_now_add=True)
    modify_date = models.DateTimeField('Modified date')

    content = models.CharField(max_length=200)
    writer = models.ForeignKey(User, null= True, on_delete=models.CASCADE)

    parent_comment = models.IntegerField(default=0)
    depth = models.IntegerField(default=0)

    def initReComment(self, parentComment):
        self.parent_comment = parentComment.id
        self.depth = 1
        return

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ('-modify_date',)

myapp/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = {'content'}

myapp/views.py
import null
from django.db.models import *
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin, ModelFormMixin

from myapp.models import Post, Comment
from django.contrib.auth import logout as django_logout
from django.shortcuts import redirect

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from newSite.views import LoginRequiredMixin
from .forms import CommentForm
import logging

def logout(request):
    django_logout(request)
    return redirect('myapp:home_view')

def updateOrder(self):
    update_posts = Post.objects.filter(g_order=self.object.g_order)
    recentOrder = Post.objects.all().order_by('-g_order')[0].g_order

    for post in update_posts:
        post.g_order = recentOrder + 1
        post.save()

    post = self.object
    post.g_order = recentOrder + 1
    post.save()

def postListView(request):
    post_list = Post.objects.all()
    if post_list != null:
        recentOrder = Post.objects.all().order_by('-g_order')[0].g_order
        for post in post_list:
            if post.g_order == 0:
                post.g_order = recentOrder+1
                post.save()

    post_list = Post.objects.all().order_by('-g_order','create_date')

    #search

    q = request.GET.get('qf','')
    if q:
        post_list = post_list.filter(title_text__icontains=q)


    page = request.GET.get('page',1)

    paginator = Paginator(post_list, 5)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'myapp/home.html', {'posts': posts})

class DetailView(FormMixin, DetailView):
    model = Post
    template_name = 'myapp/detail.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('myapp:detail', kwargs={'pk' : self.object.id})

    def get_context_data(self, **kwargs):
        context = super(DetailView,self).get_context_data(**kwargs)

        comments = Comment.objects.filter(linkedPost=kwargs['object']).order_by('modify_date')
        for comment in comments:
            if comment.depth == 0 & comment.parent_comment != comment.id:
                comment.parent_comment = comment.id
                comment.save()

        comments = comments.order_by('parent_comment','create_date',)

        context['comments'] = comments
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.linkedPost = self.get_object()
        comment.writer = self.request.user
        comment.modify_date = timezone.now()
        form.save()
        return super(DetailView,self).form_valid(form)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title_text','content']
    success_url = reverse_lazy('myapp:home_view')

    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.instance.modify_date = timezone.now()
        return super(PostCreateView,self).form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title_text', 'content']
    success_url = reverse_lazy('myapp:home_view')

    def form_valid(self, form):
        #
        updateOrder(self)
        #
        form.instance.modify_date = timezone.now()
        return super(PostUpdateView, self).form_valid(form)

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('myapp:home_view')

##
class RePostCreate(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title_text', 'content']
    template_name = 'myapp/repost_form.html'
    success_url = reverse_lazy('myapp:home_view')

    def get_parentPost(self):
        parentPost = Post.objects.get(id=self.kwargs['postId'])
        return  parentPost

    def get_context_data(self, **kwargs):
        context = super(RePostCreate,self).get_context_data(**kwargs)
        context['pp'] = self.get_parentPost()
        return context

    def form_valid(self, form):
        parentPost = self.get_parentPost()
        recentOrder = Post.objects.all().order_by('-g_order')[0].g_order

        update_posts = Post.objects.filter(g_order=parentPost.g_order)
        for post in update_posts:
            post.g_order = recentOrder + 1
            post.save()

        parentPost.g_order = recentOrder + 1
        parentPost.save()
        form.instance.initRePost(parentPost)

        form.instance.writer = self.request.user
        form.instance.modify_date = timezone.now()
        return super(RePostCreate, self).form_valid(form)

##
class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['content',]

    def get_success_url(self):
        return reverse('myapp:detail', kwargs={'pk': self.object.linkedPost.id})

    def form_valid(self, form):
        form.instance.modify_date = timezone.now()
        return super(CommentUpdateView, self).form_valid(form)

class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    def get_success_url(self):
        return reverse('myapp:detail', kwargs={'pk': self.object.linkedPost.id})

##
class ReCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']
    template_name = 'myapp/recomment_add.html'

    def get_success_url(self):
        return reverse('myapp:detail', kwargs={'pk': self.object.linkedPost.id})

    def get_context_data(self, **kwargs):
        context = super(ReCommentCreateView,self).get_context_data(**kwargs)
        context['pc'] = Comment.objects.get(id = self.kwargs['PcommentId'])
        return context

    def form_valid(self, form):
        parentComment = self.get_context_data()['pc']
        form.instance.initReComment(parentComment)
        form.instance.linkedPost = parentComment.linkedPost
        form.instance.writer = self.request.user
        form.instance.modify_date = timezone.now()
        return super(ReCommentCreateView, self).form_valid(form)

myapp/templates/myapp/add_comment_to_post.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
    <div id = 'content'>
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
    </div>
{% endblock %}

myapp/templates/myapp/comment_confirm_delete.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
    <div id = 'content'>
        <h1>댓글 삭제</h1>
        {{ comment.writer.get_username }} | {{comment.modify_date | date:"Y.m.d "}}
        <form action="" method="post">
            {% csrf_token %}
            <div id="postContent">
                <p>
                {{ comment.content }}
                </p>
            </div>
            <p>
                해당 댓글이 삭제됩니다. 삭제하시겠습니까?
            </p>
            <button type="button" onclick="location.href='{{ request.META.HTTP_REFERER }}'">취소</button>
            <input type="submit" value="삭제"/>
        </form>
    </div>
{% endblock %}

myapp/templates/myapp/comment_form.html
{% extends 'myapp/homeBar.html' %}

{% block title %}comment_form.html{% endblock %}

{% block content %}
<div id = 'content'>
    <h1>
        댓글 수정하기
    </h1>
    <h4>
        {{ object.id }} | {{ user.get_username }}
    </h4>

    <form action="" method="post" class="form">
        {% csrf_token %}
        {% if form.errors %}
            <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p> 댓글을 수정할 수 있습니다. </p>
        <fieldset class = "aligned">

            <div class="form-row">
                내용 <br/> {{ form.content }}
            </div>

        </fieldset>

        <div class="submit-row">
            <input type="submit" value="제출"/>
       </div>

    <script type="text/javascript">
        doucument.getElementById('id_content').focus();
    </script>
    </form>

</div>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
    <div id = 'content'>

        <h1>{{ post.title_text }}</h1>
        <h4>{{ post.writer.get_username }}</h4>{{ post.modify_date }}
        <br/>
        <br/>

        <div id = postContent>
                {{ post.content }}
        </div>
        {% if post.writer == user %}
           <button type="button" onclick="location.href='{% url 'myapp:update' post.id %}'">수정</button>
           <button type="button" onclick="location.href='{% url 'myapp:delete' post.id %}'">삭제</button>
        {% endif %}
        {% if post.depth == 0 %}
                {% if user.is_active %}
                    <button type="button" onclick="location.href='{% url 'myapp:add_repost' post.id %}'">답글</button>
                {% else %}
                    <button type="button" onclick="location.href='{% url 'login'%}'">답글</button>

                {% endif %}
        {% endif %}
        <p>------------------------------</p>

        <div id = 'postComment'>
            <p>
                {% for comment in comments %}
                    <h4>
                        {% if comment.depth == 0 %}
                            {{ comment.content }} | {{ comment.writer.get_username }} | {{ comment.create_date }} 생성 됨
                            <button type="button" onclick="location.href='{% url 'myapp:add_recomment' comment.id %}'">댓글</button>
                        {% else %}
                            ㄴ&gt;
                            {{ comment.content }} | {{ comment.writer.get_username }} | {{ comment.create_date }} 생성 됨
                        {% endif %}

                    {% if comment.writer == user  %}
                        <button type="button" onclick="location.href='{% url 'myapp:comment_update' post.id comment.id %}'">수정</button>
                        <button type="button" onclick="location.href='{% url 'myapp:comment_delete' post.id comment.id %}'">삭제</button>
                    {% endif %}
                    </h4>
                {% endfor %}
            </p>
        </div>

        <div id = 'createComment'>
            <form method="post">
            {% csrf_token %}
                댓글 {{ form.content }}
               {% if user.is_active == False %}
                    <button type="button" onclick="location.href='{% url 'login' %}'">등록</button>
                {% else %}
                    <input type="submit" value="제출">
                {% endif %}
            </form>
        </div>
    </div>


{% endblock content%}

myapp/templates/myapp/home.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
    <div id="content">

        <h1>Blog List</h1>


        <div id="postList">
            {% for post in posts %}
                <h2>
                    <a href="{{ post.id }}">
                        {% if post.depth == 2 %}
                        ㄴ&gt;ㄴ&gt;
                        {% elif post.depth == 1 %}
                        ㄴ&gt;
                        {% else %}
                        {% endif %}
                        {{ post.title_text }} | {{ post.writer.get_username }}
                        {% if post.get_comment_count != 0 %}
                            ({{ post.get_comment_count }})
                        {% endif %}
                    </a>
                    {% if post.writer == user %}
                        &nbsp;
                        <button type="button" onclick="location.href='{% url 'myapp:update' post.id %}'">수정</button>
                        <button type="button" onclick="location.href='{% url 'myapp:delete' post.id %}'">삭제</button>
                    {% endif %}
                </h2>

            {% endfor %}
        </div>


        <div id = "pagination">
            {% if posts.has_other_pages %}
                <h2>
                {% if posts.has_previous %}
                   <a href="?page={{ posts.previous_page_number }}">&laquo;</a>
                {% else %}
                    <span>&laquo;</span>
                {% endif %}
                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <span><strong>[{{ i }}]</strong></span>
                    {% else %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">&raquo;</a>
                {% else %}
                    <span>&raquo;</span>
                {% endif %}
                </h2>
            {% endif %}
        </div>

        <div id = "searchField">
            <form action="" method="get">
                <input type="text" name="qf" value="{{ q }}">
                <input type="submit" value="검색">
                {% if user.is_active %}
                <button type="button" onclick="location.href='{% url 'myapp:add' %}'">글쓰기</button>
                {% else %}
                {% endif %}
            </form>
        </div>

    </div>

    <br>

{% endblock content%}

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
    <div id = 'content'>
        <h1>Post 삭제</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div id="postContent">
                <p>
                {{post.modify_date | date:"Y.m.d "}} | {{ post.title_text }} | {{ post.writer.get_username }}
                </p>
            </div>
            <p>
                해당 포스트가 삭제됩니다. 삭제하시겠습니까?
            </p>
            <button type="button" onclick="location.href='{{ request.META.HTTP_REFERER }}'">취소</button>
            <input type="submit" value="삭제"/>
        </form>
    </div>
{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/homeBar.html' %}

{% block title %}post_form.html{% endblock %}

{% block content %}
<div id = 'content'>
    <h1>
        Post 작성하기
    </h1>
    <h4>
        {{ user.get_username }}
    </h4>

    <form action="." method="post">
        {% csrf_token %}
        {% if form.errors %}
            <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p> 새로운 포스트를 작성하거나 수정할 수 있습니다. </p>
        <fieldset class = "aligned">
            <div class = 'form-row'>
                제목 <br/> {{ form.title_text }}
            </div>

            <div class="form-row">
                내용 <br/> {{ form.content }}
            </div>

        </fieldset>

        <div class="submit-row">
            <input type="submit" value="제출"/>
       </div>

    <script type="text/javascript">
        doucument.getElementById('id_title_text').focus();
    </script>
    </form>

</div>
{% endblock %}

myapp/templates/myapp/recomment_add.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
<div id = 'content'>
    <h1>
        답변 달기
    </h1>
    <h4>
        {{ object.id }} | {{ user.get_username }}
    </h4>

    <form action="" method="post" class="form">
        {% csrf_token %}
        {% if form.errors %}
            <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p> 댓글에 대한 답변을 입력 할 수 있습니다. </p>
        <fieldset class = "aligned">

            <div class="form-row">
                내용 <br/> {{ form.content }}
            </div>

        </fieldset>

        <div class="submit-row">
            <input type="submit" value="제출"/>
       </div>

    <script type="text/javascript">
        doucument.getElementById('id_content').focus();
    </script>
    </form>

</div>
{% endblock %}

myapp/templates/myapp/repost_form.html
{% extends 'myapp/homeBar.html' %}

{% block content %}
<div id = 'content'>
    <h1>
        {{ pp.id }} Post 답글 작성하기
    </h1>
    <h4>
        {{ user.get_username }}
    </h4>

    <form action="." method="post">
        {% csrf_token %}
        {% if form.errors %}
            <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p> 해당 포스트에 대한 답글을 작성하거나 수정할 수 있습니다. </p>
        <fieldset class = "aligned">
            <div class = 'form-row'>
                제목 <br/> {{ form.title_text }}
            </div>

            <div class="form-row">
                내용 <br/> {{ form.content }}
            </div>

        </fieldset>

        <div class="submit-row">
            <input type="submit" value="제출"/>
       </div>

    <script type="text/javascript">
        doucument.getElementById('id_title_text').focus();
    </script>
    </form>

</div>
{% endblock %}